flaskr/views.py

from datetime import datetime
from flask import (
    Blueprint, abort, request, render_template,
    redirect, url_for, flash, session, jsonify, 
)
from flask_login import login_user, logout_user, login_required, current_user
from flaskr.models import User, PasswordResetToken, UserConnect, Message
from flaskr import db
from flaskr.forms import (
    LoginForm, RegisterForm, ResetPasswordForm, ForgotPasswordForm,
    UserForm, ChangePasswordForm, UserSearchForm, ConnectForm, MessageForm,

)
from flaskr.utils.message_format import make_message_format, make_old_message_format
from os import path

# メソッドの前にappを付ける必要がでてくる
bp = Blueprint('app', __name__, url_prefix='')

# @bp.route('/')
# def home():
#     """ 友達一覧表示 """
#     user_id = current_user.get_id()
#     user_friends_id_to_from, user_friends_id_from_to = User.find_friends_id(user_id)
#     # ログインユーザ空間から検索ユーザ空間に写像するためにlistの変換が必要
#     friends_id_list = []
#     for user_friend_id in user_friends_id_to_from:
#         if user_friend_id.friends_to_from:
#             friends_id_list.append(user_friend_id.friends_to_from)
#     for user_friend_id in user_friends_id_from_to:
#         if user_friend_id.friends_from_to:
#             friends_id_list.append(user_friend_id.friends_from_to)
#     friends = []
#     for friends_id in friends_id_list:
#         friends.append(User.select_user_by_id(friends_id))

#     """ 友達非承認待ち """
#     requested_friends_records = UserConnect.find_friends_requested(user_id)
#     requested_friends_records_list = []
#     for requested_friend_record in requested_friends_records:
#         requested_friends_records_list.append(requested_friend_record.from_user_id)
#     requested_friends = []
#     for requested_friend_id in requested_friends_records_list:
#         requested_friends.append(User.select_user_by_id(requested_friend_id))

#     connect_form = ConnectForm()
#     session['url'] = 'app.home'
#     return render_template('home.html', friends=friends, requested_friends=requested_friends, connect_form=connect_form)


@bp.route('/')
def home():
    friends = requested_friends = requesting_friends = None
    connect_form = ConnectForm()
    session['url'] = 'app.home'
    if current_user.is_authenticated:
        friends = User.select_friends()
        requested_friends = User.select_requested_friends()
        requesting_friends = User.select_requesting_friends()
    return render_template(
        'home.html',
        friends=friends, requested_friends=requested_friends, requesting_friends=requesting_friends,
        connect_form=connect_form
    )


@bp.route('/logout')
def logout():
    """ ユーザのセッションを切ってくれる """
    logout_user()
    return redirect(url_for('app.home'))


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        """ http.postかつformのvalidaterが正常な場合 """
        user = User.select_user_by_email(form.email.data)
        if user and user.is_active and user.validate_password(form.password.data):
            login_user(user, remember=True)
            next = request.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
        elif not user:
            flash('存在しないユーザ、ってかflashって何！？')
        elif not user.is_active:
            flash('無効になっとるユーザや！')
        elif not user.validate_password(form.password.data):
            flash('メールアドレスとパスワードのCombが誤っています')
    return render_template('login.html', form=form)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            username = form.username.data,
            email = form.email.data,
        )
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()
        token = ''
        with db.session.begin(subtransactions=True):
            token = PasswordResetToken.publish_token(user)
        db.session.commit()
        print(f'パスワード設定用URL：http://127.0.0.1:5000/set_password/{token}')
        flash('パスワード設定用のURLを表示しました')
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)


@bp.route('/set_password/<uuid:token>', methods=['GET', 'POST'])
def set_password(token):
    form = ResetPasswordForm(request.form)
    reset_user_id = PasswordResetToken.get_user_id_by_token(token)
    if not reset_user_id:
        abort(500)
    if request.method == 'POST' and form.validate():
        password = form.password.data
        user = User.select_user_by_id(reset_user_id)
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
            PasswordResetToken.delete_token(token)
        db.session.commit()
        flash('パスワードは無事に更新されました')
        return redirect(url_for('app.login'))
    return render_template('set_password.html', form=form)


@bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        email = form.email.data
        user = User.select_user_by_email(email)
        if user:
            with db.session.begin(subtransactions=True):
                token = PasswordResetToken.publish_token(user)
            db.session.commit()
            reset_url = f'http://127.0.0.1:5000/set_password/{token}'
            print(reset_url)
            flash('パスワード設定用のURLを表示しました')
        else:
            flash('存在しないユーザです')
    return render_template('forgot_password.html', form=form)


@bp.route('/user', methods=['GET', 'POST'])
def user():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        user_id = current_user.get_id()
        user = User.select_user_by_id(user_id)
        with db.session.begin(subtransactions=True):
            user.username = form.username.data
            user.email = form.email.data
            # fileデータは処理が違う
            file = request.files[form.picture_path.name].read()
            if file:
                """ 上のファイル名でファイルが存在していたら """
                file_name = user_id + '_' + str(int(datetime.now().timestamp())) + '.jpg'
                picture_path = 'flaskr/static/user_image/' + file_name
                # picture_pathに画像ファイルのバイナリデータを記述する
                open(picture_path, 'wb').write(file)
                user.picture_path = 'user_image/' + file_name
        db.session.commit()
        flash('ユーザ情報の更新に成功しました')
    return render_template('user.html', form=form)


@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_id(current_user.get_id())
        password = form.password.data
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
        db.session.commit()
        flash('パスワードの更新に成功しました')
        return redirect(url_for('app.user'))
    return render_template('change_password.html', form=form)


@bp.route('/user_search', methods=['GET'])
@login_required
def user_search():
    form = UserSearchForm(request.form)
    connect_form = ConnectForm()
    session['url'] = 'app.user_search'
    users = None
    user_name = request.args.get('username', None, type=str)
    next_url = prev_url = None
    if user_name:
        page = request.args.get('page', 1, type=int)
        # postsはflask_sqlalchemy.Paginationクラスを継承している
        posts = User.search_by_name(user_name, page)
        next_url = url_for('app.user_search', page=posts.next_num, username=user_name) if posts.has_next else None
        prev_url = url_for('app.user_search', page=posts.prev_num, username=user_name) if posts.has_prev else None
        users = posts.items
        # UserからUserConnectのStatusを取得する
    return render_template('user_search.html', form=form, users=users, connect_form=connect_form,
        next_url=next_url, prev_url=prev_url)


@bp.route('/connect_user', methods=['POST'])
@login_required
def connect_user():
    form = ConnectForm(request.form)
    if request.method == 'POST' and form.validate():
        if form.connect_condition.data == 'connect':
            new_connect = UserConnect(current_user.get_id(), form.to_user_id.data)
            with db.session.begin(subtransactions=True):
                new_connect.create_new_connect()
            db.session.commit()
        elif form.connect_condition.data == 'accept':
            # 相手から自分へのUserConnectを取得
            connect = UserConnect.select_by_from_user_id(form.to_user_id.data)
            if connect:
                with db.session.begin(subtransactions=True):
                    connect.update_status() # status 1 -> 2
                db.session.commit()
    # user_searchから取得したsessionを利用する
    next_url = session.pop('url', 'app:home')
    return redirect(url_for(next_url))


@bp.route('/delete_connect', methods=['POST'])
@login_required
def delete_connect():
    """ UserConnectから対応レコードを削除 """
    form = ConnectForm(request.form)
    if request.method == 'POST':
        if form.connect_condition.data == 'delete':
            if UserConnect.select_by_from_user_id(form.to_user_id.data):
                delete_connect = UserConnect.select_by_from_user_id(form.to_user_id.data)
                with db.session.begin(subtransactions=True):
                    db.session.delete(delete_connect)
                db.session.commit()
            elif UserConnect.select_by_to_user_id(form.to_user_id.data):
                delete_connect = UserConnect.select_by_to_user_id(form.to_user_id.data)

flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{field.label}}
    <dd>
        {{field(**kwargs) | safe}}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{error}}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>

{% endmacro %}



flaskr/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{% block title %}FLASK SNS{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="icon" href="{{url_for('static', filename='icon/Glaceon_squares.png')}}">
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{url_for('app.home')}}">
            ホーム
        </a>
        {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="{{url_for('app.logout')}}">
            ログアウト
        </a>
        <a class="navbar-brand" href="{{url_for('app.user')}}">
            ユーザ情報編集画面
        </a>
        <a class="navbar-brand" href="{{url_for('app.user_search')}}">
            ユーザ検索画面
        </a>
        {% else %}
        <a class="navbar-brand" href="{{url_for('app.login')}}">
            ログイン
        </a>
        <a class="navbar-brand" href="{{url_for('app.register')}}">
            登録
        </a>
        {% endif %}
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

flaskr/templates/change_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更画面 - {{super()}}
{% endblock %}

{% block content %}
<h1>パスワード変更画面</h1>

<div class="row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.password)}}
        {{render_field(form.confirm_password)}}
        {{form.submit()}}
    </form>
</div>
{% endblock %}



flaskr/templates/forgot_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
Reset_Password - {{super()}}
{% endblock %}

{% block content %}
{% for message in get_flashed_messages() %}
{{message}}
{% endfor %}
<h1>パスワード再発行画面</h1>

<div class="row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.email)}}
        {{form.submit()}}
    </form>
</div>
{% endblock %}



flaskr/templates/home.html
{% extends "base.html" %}
{% block title %}
Home - {{super()}}
{% endblock %}

{% block content %}
<div class="row">
    {% if current_user.is_authenticated %}
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
            <img class="user-image-big" src="{{url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <p>ユーザ名：{{current_user.username}}</p>
        <p>メールアドレス：{{current_user.email}}</p>
        <!-- 友達一覧表示 -->
        <div class="col-lg-12">
            <h2>友達一覧</h2>
            <table class="table table-bordered">
                <!-- テーブルのヘッダー -->
                <thead>
                    <tr>
                        <th>#</th>
                        <th>友達画像</th>
                        <th>友達の名前</th>
                        <th>メッセージ</th>
                        <th>友達解消ボタン</th>
                    </tr>
                </thead>
                <!-- テーブルのボディ -->
                {% if friends %}
                <tbody>
                    {% for friend in friends %}
                    <tr>
                        <td>{{loop.index}}</td>
                        {% if friend.picture_path %}
                        <td>
                            <img class="user-image-small" src="{{url_for('static', filename=friend.picture_path)}}">
                        </td>
                        {% else %}
                        <td></td>
                        {% endif %}
                        <td>{{friend.username}}</td>
                        <td><a href="{{url_for('app.message', id=friend.id)}}" class="btn btn-link">メッセージを送る</a></td>
                        <td>
                            <form method="POST" action="{{url_for('app.delete_connect')}}">
                                {{connect_form.csrf_token}}
                                {{connect_form.connect_condition(value='delete')}}
                                {{connect_form.to_user_id(value=friend.id)}}
                                {{connect_form.submit(class='btn btn-primary', value='友達を解消する')}}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
                {% endif %}
            </table>
        </div>
        <!-- 非承認待ち一覧表示 -->
        <div class="col-lg-12">
            {% if requested_friends %}
            <table class="table table-bordered">
                <!-- テーブルのヘッダー -->
                <thead>
                    <tr>
                        <th>#</th>
                        <th>承認リクエストユーザ画像</th>
                        <th>承認リクエストユーザ</th>
                        <th>承認ボタン</th>
                    </tr>
                </thead>
                <!-- テーブルのボディ -->
                <tbody>
                    {% for requested_friend in requested_friends %}
                    <tr>
                        <td>{{loop.index}}</td>
                        {% if requested_friend.picture_path %}
                        <td>
                            <img class="user-image-small" src="{{url_for('static', filename=requested_friend.picture_path)}}">
                        </td>
                        {% else %}
                        <td></td>
                        {% endif %}
                        <td>{{requested_friend.username}}</td>
                        <td>
                            <form method="POST" action="{{url_for('app.connect_user')}}">
                                <!-- forms.pyから取得せず、ただviews.pyに変数を返すだけのフォーム -->
                                {{connect_form.csrf_token}}
                                {{connect_form.connect_condition(value='accept')}}
                                {{connect_form.to_user_id(value=requested_friend.id)}}
                                {{connect_form.submit(class='btn btn-primary', value='友達申請を承認')}}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
            {% endif %}
        </div>

    {% else %}
        <p>ログインしてくださいな</p>
    {% endif %}
    </div>
    
</div>
{% endblock %}



flaskr/templates/http500.html
<h1>サーバーエラーぽよ。シス管に問い合わせてね</h1>

flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
Login - {{super()}}
{% endblock %}

{% block content %}
{% for message in get_flashed_messages() %}
{{message}}
{% endfor %}
<div class="row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.email)}}
        {{render_field(form.password)}}
        {{render_field(form.confirm_password)}}
        {{form.submit()}}
    </form>
    <a href="{{url_for('app.forgot_password')}}">
        パスワードを忘れた場合はこちら
    </a>
</div>
{% endblock %}



flaskr/templates/message.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
メッセージ画面 - {{super()}}
{% endblock %}
{% block content %}
    <script>
        // Ajaxで5秒間隔でメッセージをサーバから取得する
        $(function(){
            timer = setInterval("get_new_messages()", 5000);
            // 初期表示で画面の一番下にいく
            var scroll = (document.scrollingElement || document.body);
            scroll.scrollTop = scroll.scrollHeight;
        });
        user_id = "{{to_user_id}}";
        offset_value = 1;
        function get_new_messages(){
            // 定期実行する関数を定義
            // views.pyの/message_ajaxと対応
            $.getJSON("/message_ajax", {
                user_id: user_id
            }, function(data){
                $('#message-form').before(data['data']);
                var checked_message_ids = data['checked_message_ids'];
                for(let idx = 0; idx < checked_message_ids.length; idx++){
                    $('#self-message-tag-' + checked_message_ids[idx]).append('<p>既読</p>');
                }
            });
        };
        function load_old_messages(){
            $.getJSON("/load_old_messages", {
                user_id: user_id,
                offset_value: offset_value
            }, function(data){
                if(data['data']){
                    hidden_id = "load_message_" + offset_value;
                    hidden_tag = '<div id="' + hidden_id + '"></div>';
                    $(hidden_tag).insertAfter('#load_message_button');
                    $(data['data']).insertAfter('#load_message_button');
                    $('body, html').animate({scrollTop: $("#" + hidden_id).offset().top}, 0);
                    offset_value += 1;
                }
            });
        };
    </script>
<!-- BootstrapのGridSystemは横幅合計を12にする必要がある -->
    <div class="row">
        <div id="load_message_button" class="col-12">
            <button class="col-12 btn btn-light btn-outline-primary" onclick="load_old_messages();">追加でメッセージを読み込む</button>
        </div>
        {% for message in messages|reverse %}
            {% if message.from_user_id == current_user.id %}
            <!-- 自分側 -->
            <div class="col-md-2">
                {% if current_user.picture_path %}
                <img class="user-image-mini" src="{{url_for('static', filename=current_user.picture_path)}}">
                {% endif %}
                <p>{{current_user.username}}</p>
            </div>
            <div class="speech-bubble-self col-md-4">
                {% for splitted_message in message.message | replace_newline %}
                <p>{{splitted_message | urlize(target=true)}}</p>
                {% endfor %}
                <p>{{message.create_at.strftime("%H:%M")}}</p>
            </div>
            <div id="self-message-tag-{{message.id}}" class="col-md-2">
                {% if message.is_checked %}
                <p>既読</p>
                {% endif %}
            </div>
            <div class="col-md-4"></div>
            {% else %}
            <!-- 相手側 -->
            <div class="col-md-6"></div>
            <div class="speech-bubble-dest col-md-4">
                {% for splitted_message in message.message | replace_newline %}
                <p>{{splitted_message | urlize(target=true)}}</p>
                {% endfor %}
                <p>{{message.create_at.strftime("%H:%M")}}</p>
            </div>
            <div class="col-md-2">
                {% if user.picture_path %}
                <img class="user-image-mini" src="{{url_for('static', filename=user.picture_path)}}">
                {% endif %}
                <p>{{user.username}}</p>
            </div>
            {% endif %}
        {% endfor %}

        <div id="message-form" class="col-md-4">
            <form method="POST">
                {{form.csrf_token}}
                {{form.to_user_id(value=to_user_id)}}
                {{render_field(form.message, cols="50", rows="5")}}
                {{form.submit()}}
            </form>
        </div>
    </div>



{% endblock %}

flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
Register - {{super()}}
{% endblock %}

{% block content %}
<h1>ユーザ情報登録画面</h1>

<div class="row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.username)}}
        {{render_field(form.email)}}
        {{form.submit()}}
    </form>
</div>
{% endblock %}



flaskr/templates/set_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
Password - {{super()}}
{% endblock %}

{% block content %}
<h1>パスワード登録画面</h1>

<div class="row">
    <form method="POST">
        {{form.csrf_token}}
        {{render_field(form.password)}}
        {{render_field(form.confirm_password)}}
        {{form.submit()}}
    </form>
</div>
{% endblock %}



flaskr/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザ情報編集画面 - {{super()}}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 offset-lg-4">
    {% for message in get_flashed_messages() %}
    {{message}}
    {% endfor %}
    </div>
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
        <img class="user-image-big" src="{{url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <form method="POST" enctype="multipart/form-data">
            {{form.csrf_token}}
            {{render_field(form.username, value=current_user.username)}}
            {{render_field(form.email, value=current_user.email)}}
            {{render_field(form.picture_path)}}
            {{form.submit()}}
        </form>
        <a href="{{url_for('app.change_password')}}">パスワードを変更する</a>
    </div>
</div>
{% endblock %}



flaskr/templates/user_search.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザ検索 - {{super()}}
{% endblock %}

{% block content %}
<div class="jumbotron">
    <p>ユーザ検索画面</p>
</div>
<div class="row">
    <div class="col-lg-12">
        <form method="GET">
            {{form.csrf_token}}
            {{render_field(form.username)}}
            {{form.submit()}}
        </form>
    </div>
    <div class="col-lg-12">
        {% if users %}
        <table class="table">
            <!-- テーブルのヘッダー -->
            <thead>
                <tr>
                    <th>#</th>
                    <th>ユーザ画像</th>
                    <th>ユーザ名</th>
                    <th>申請ボタン</th>
                </tr>
            </thead>
            <!-- テーブルのボディ -->
            <tbody>
                {% for user in users %}
                <tr>
                    <th>{{loop.index}}</th>
                    {% if user.picture_path %}
                    <th>
                        <img class="user-image-small" src="{{url_for('static', filename=user.picture_path)}}">
                    </th>
                    {% else %}
                    <th></th>
                    {% endif %}
                    <th>{{user.username}}</th>
                    <th>
                        {% if user.joined_status_from_to == 2 or user.joined_status_to_from == 2 %}
                        友達です♡
                        {% elif user.joined_status_from_to == 1 %}
                        友達申請中。お返事を待ってね
                        {% elif user.joined_status_to_from == 1 %}
                        <form method="POST" action="{{url_for('app.connect_user')}}">
                            <!-- forms.pyから取得せず、ただviews.pyに変数を返すだけのフォーム -->
                            {{connect_form.csrf_token}}
                            {{connect_form.connect_condition(value='accept')}}
                            {{connect_form.to_user_id(value=user.id)}}
                            {{connect_form.submit(class='btn btn-primary', value='友達申請を承認')}}
                        </form>
                        {% else %}
                        <form method="POST" action="{{url_for('app.connect_user')}}">
                            {{connect_form.csrf_token}}
                            {{connect_form.connect_condition(value='connect')}}
                            {{connect_form.to_user_id(value=user.id)}}
                            {{connect_form.submit(class='btn btn-primary', value='友達申請する')}}
                        </form>
                        {% endif %}
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if prev_url %}
            <a href="{{prev_url}}">前へ</a>
        {% endif %}
        {% if next_url %}
            <a href="{{next_url}}">次へ</a>
        {% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}
